analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_key_in_widget_constructors: ignore
    unused_local_variable: warning

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
